### ISSUE TITLE
satellite_gps_center.npy files

### ISSUE THREAD

**Issue by WoojuLee24** [ShanWang-Shan/SIBCL#1]
Hello, thank you for your work.
It seems that some files are missing: "satellite_gps_center.npy and groundview_satellite_pair_18.npy"
groundview_satellite_pair_18.npy is generated from satellite_gps_center.npy, so satellite_gps_center.npy is required to run the code.
Could you upload the satellite_gps_center.npy or provide links to download? 
Thank you.

**Comment by ShanWang-Shan** [comment]
Please find the required file at the following link:
https://drive.google.com/drive/folders/1DML0ryEERCs1uiM501I-MJxSCjXaFFdS?usp=sharing

Additionally, 'groundview_satellite_pair.npy' is generated using 'kitti_data_process/kitti_cross_view_pair.py,' and you can find the code for 'satellite_gps_center.npy' generation for Ford-CVL in 'ford_data_process/get_gps_coverage.py.'

**Comment by WoojuLee24** [comment]
Thanks for your kind explanation. I ran the code successfully !
